services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  KayStrobach\DyncssLess\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Parser/*'
  KayStrobach\DyncssLess\Hooks\T3libPageRendererRenderPreProcessHook:
    public: true
